# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mining_optimizer_template.ui'
#
# Created: Thu Feb 25 00:19:39 2010
#      by: PyQt4 UI code generator 4.7
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_mining_optimizer_window(object):
    def setupUi(self, mining_optimizer_window):
        mining_optimizer_window.setObjectName("mining_optimizer_window")
        mining_optimizer_window.resize(682, 412)
        self.centralwidget = QtGui.QWidget(mining_optimizer_window)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.mineral_tree = QtGui.QTreeWidget(self.groupBox)
        self.mineral_tree.setObjectName("mineral_tree")
        self.verticalLayout_3.addWidget(self.mineral_tree)
        self.horizontalLayout_4.addWidget(self.groupBox)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.station_label = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.station_label.sizePolicy().hasHeightForWidth())
        self.station_label.setSizePolicy(sizePolicy)
        self.station_label.setObjectName("station_label")
        self.horizontalLayout.addWidget(self.station_label)
        self.station_combo = QtGui.QComboBox(self.centralwidget)
        self.station_combo.setObjectName("station_combo")
        self.horizontalLayout.addWidget(self.station_combo)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.character_label = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.character_label.sizePolicy().hasHeightForWidth())
        self.character_label.setSizePolicy(sizePolicy)
        self.character_label.setMinimumSize(QtCore.QSize(0, 0))
        self.character_label.setObjectName("character_label")
        self.horizontalLayout_2.addWidget(self.character_label)
        self.character_combo = QtGui.QComboBox(self.centralwidget)
        self.character_combo.setObjectName("character_combo")
        self.horizontalLayout_2.addWidget(self.character_combo)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.mine_tree = QtGui.QTreeWidget(self.groupBox_2)
        self.mine_tree.setObjectName("mine_tree")
        self.verticalLayout_2.addWidget(self.mine_tree)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        mining_optimizer_window.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(mining_optimizer_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 682, 22))
        self.menubar.setObjectName("menubar")
        mining_optimizer_window.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(mining_optimizer_window)
        self.statusbar.setObjectName("statusbar")
        mining_optimizer_window.setStatusBar(self.statusbar)

        self.retranslateUi(mining_optimizer_window)
        QtCore.QMetaObject.connectSlotsByName(mining_optimizer_window)
        mining_optimizer_window.setTabOrder(self.station_combo, self.character_combo)
        mining_optimizer_window.setTabOrder(self.character_combo, self.mineral_tree)
        mining_optimizer_window.setTabOrder(self.mineral_tree, self.mine_tree)

    def retranslateUi(self, mining_optimizer_window):
        mining_optimizer_window.setWindowTitle(QtGui.QApplication.translate("mining_optimizer_window", "Mining Optimizer", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("mining_optimizer_window", "Requested Minerals", None, QtGui.QApplication.UnicodeUTF8))
        self.mineral_tree.headerItem().setText(0, QtGui.QApplication.translate("mining_optimizer_window", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.mineral_tree.headerItem().setText(1, QtGui.QApplication.translate("mining_optimizer_window", "Amount", None, QtGui.QApplication.UnicodeUTF8))
        self.mineral_tree.headerItem().setText(2, QtGui.QApplication.translate("mining_optimizer_window", "Price", None, QtGui.QApplication.UnicodeUTF8))
        self.mineral_tree.headerItem().setText(3, QtGui.QApplication.translate("mining_optimizer_window", "Total", None, QtGui.QApplication.UnicodeUTF8))
        self.mineral_tree.headerItem().setText(4, QtGui.QApplication.translate("mining_optimizer_window", "Volume", None, QtGui.QApplication.UnicodeUTF8))
        self.station_label.setText(QtGui.QApplication.translate("mining_optimizer_window", "Station", None, QtGui.QApplication.UnicodeUTF8))
        self.character_label.setText(QtGui.QApplication.translate("mining_optimizer_window", "Character", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("mining_optimizer_window", "Which Ores To Mine", None, QtGui.QApplication.UnicodeUTF8))
        self.mine_tree.headerItem().setText(0, QtGui.QApplication.translate("mining_optimizer_window", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.mine_tree.headerItem().setText(1, QtGui.QApplication.translate("mining_optimizer_window", "Amount", None, QtGui.QApplication.UnicodeUTF8))
        self.mine_tree.headerItem().setText(2, QtGui.QApplication.translate("mining_optimizer_window", "Price", None, QtGui.QApplication.UnicodeUTF8))
        self.mine_tree.headerItem().setText(3, QtGui.QApplication.translate("mining_optimizer_window", "Total", None, QtGui.QApplication.UnicodeUTF8))
        self.mine_tree.headerItem().setText(4, QtGui.QApplication.translate("mining_optimizer_window", "Volume", None, QtGui.QApplication.UnicodeUTF8))
        self.mine_tree.headerItem().setText(5, QtGui.QApplication.translate("mining_optimizer_window", "ISK/m³", None, QtGui.QApplication.UnicodeUTF8))

