# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mining_optimizer_template.ui'
#
# Created: Sun Jan 31 12:28:42 2010
#      by: PyQt4 UI code generator 4.7-snapshot-20091207
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_mining_optimizer_window(object):
    """
     # PyUML: Do not remove this line! # XMI_ID:_EIXh0xEREd-LgJ4IxcJkTA
    """
    def setupUi(self, mining_optimizer_window):
        mining_optimizer_window.setObjectName("mining_optimizer_window")
        mining_optimizer_window.resize(682, 343)
        self.centralwidget = QtGui.QWidget(mining_optimizer_window)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.treeWidget = QtGui.QTreeWidget(self.groupBox)
        self.treeWidget.setObjectName("treeWidget")
        self.verticalLayout_3.addWidget(self.treeWidget)
        self.horizontalLayout_4.addWidget(self.groupBox)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox = QtGui.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout.addWidget(self.comboBox)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.comboBox_2 = QtGui.QComboBox(self.centralwidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout_2.addWidget(self.comboBox_2)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.treeWidget_2 = QtGui.QTreeWidget(self.groupBox_2)
        self.treeWidget_2.setObjectName("treeWidget_2")
        self.verticalLayout_2.addWidget(self.treeWidget_2)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        mining_optimizer_window.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(mining_optimizer_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 682, 22))
        self.menubar.setObjectName("menubar")
        mining_optimizer_window.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(mining_optimizer_window)
        self.statusbar.setObjectName("statusbar")
        mining_optimizer_window.setStatusBar(self.statusbar)

        self.retranslateUi(mining_optimizer_window)
        QtCore.QMetaObject.connectSlotsByName(mining_optimizer_window)
        mining_optimizer_window.setTabOrder(self.comboBox, self.comboBox_2)
        mining_optimizer_window.setTabOrder(self.comboBox_2, self.treeWidget)
        mining_optimizer_window.setTabOrder(self.treeWidget, self.treeWidget_2)

    def retranslateUi(self, mining_optimizer_window):
        mining_optimizer_window.setWindowTitle(QtGui.QApplication.translate("mining_optimizer_window", "Mining Optimizer", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("mining_optimizer_window", "Needed Materials", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(0, QtGui.QApplication.translate("mining_optimizer_window", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(1, QtGui.QApplication.translate("mining_optimizer_window", "Amount", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(2, QtGui.QApplication.translate("mining_optimizer_window", "Price", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(3, QtGui.QApplication.translate("mining_optimizer_window", "Total", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(4, QtGui.QApplication.translate("mining_optimizer_window", "Volume", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("mining_optimizer_window", "Station", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("mining_optimizer_window", "Character", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("mining_optimizer_window", "Which Ores To Mine", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.headerItem().setText(0, QtGui.QApplication.translate("mining_optimizer_window", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.headerItem().setText(1, QtGui.QApplication.translate("mining_optimizer_window", "Amount", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.headerItem().setText(2, QtGui.QApplication.translate("mining_optimizer_window", "Price", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.headerItem().setText(3, QtGui.QApplication.translate("mining_optimizer_window", "Total", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.headerItem().setText(4, QtGui.QApplication.translate("mining_optimizer_window", "Volume", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.headerItem().setText(5, QtGui.QApplication.translate("mining_optimizer_window", "ISK/m³", None, QtGui.QApplication.UnicodeUTF8))

