//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.04.30 at 05:10:55 PM CEST 
//


package model.api.character.killmails;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}victim" minOccurs="0"/>
 *         &lt;element ref="{}rowset" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="allianceID" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="allianceName" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="characterID" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="characterName" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="corporationID" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="corporationName" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="damageDone" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="finalBlow" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="flag" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="killID" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="killTime" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="moonID" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="qtyDestroyed" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="qtyDropped" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="securityStatus" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="shipTypeID" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="solarSystemID" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="typeID" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="weaponTypeID" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "victim",
    "rowset"
})
@XmlRootElement(name = "row")
public class Row {

    protected Victim victim;
    protected Rowset rowset;
    @XmlAttribute
    protected BigInteger allianceID;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String allianceName;
    @XmlAttribute
    protected BigInteger characterID;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String characterName;
    @XmlAttribute
    protected BigInteger corporationID;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String corporationName;
    @XmlAttribute
    protected BigInteger damageDone;
    @XmlAttribute
    protected BigInteger finalBlow;
    @XmlAttribute
    protected BigInteger flag;
    @XmlAttribute
    protected BigInteger killID;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String killTime;
    @XmlAttribute
    protected BigInteger moonID;
    @XmlAttribute
    protected BigInteger qtyDestroyed;
    @XmlAttribute
    protected BigInteger qtyDropped;
    @XmlAttribute
    protected BigDecimal securityStatus;
    @XmlAttribute
    protected BigInteger shipTypeID;
    @XmlAttribute
    protected BigInteger solarSystemID;
    @XmlAttribute
    protected BigInteger typeID;
    @XmlAttribute
    protected BigInteger weaponTypeID;

    /**
     * Gets the value of the victim property.
     * 
     * @return
     *     possible object is
     *     {@link Victim }
     *     
     */
    public Victim getVictim() {
        return victim;
    }

    /**
     * Sets the value of the victim property.
     * 
     * @param value
     *     allowed object is
     *     {@link Victim }
     *     
     */
    public void setVictim(Victim value) {
        this.victim = value;
    }

    /**
     * Gets the value of the rowset property.
     * 
     * @return
     *     possible object is
     *     {@link Rowset }
     *     
     */
    public Rowset getRowset() {
        return rowset;
    }

    /**
     * Sets the value of the rowset property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rowset }
     *     
     */
    public void setRowset(Rowset value) {
        this.rowset = value;
    }

    /**
     * Gets the value of the allianceID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAllianceID() {
        return allianceID;
    }

    /**
     * Sets the value of the allianceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAllianceID(BigInteger value) {
        this.allianceID = value;
    }

    /**
     * Gets the value of the allianceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAllianceName() {
        return allianceName;
    }

    /**
     * Sets the value of the allianceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAllianceName(String value) {
        this.allianceName = value;
    }

    /**
     * Gets the value of the characterID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCharacterID() {
        return characterID;
    }

    /**
     * Sets the value of the characterID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCharacterID(BigInteger value) {
        this.characterID = value;
    }

    /**
     * Gets the value of the characterName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCharacterName() {
        return characterName;
    }

    /**
     * Sets the value of the characterName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCharacterName(String value) {
        this.characterName = value;
    }

    /**
     * Gets the value of the corporationID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCorporationID() {
        return corporationID;
    }

    /**
     * Sets the value of the corporationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCorporationID(BigInteger value) {
        this.corporationID = value;
    }

    /**
     * Gets the value of the corporationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorporationName() {
        return corporationName;
    }

    /**
     * Sets the value of the corporationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorporationName(String value) {
        this.corporationName = value;
    }

    /**
     * Gets the value of the damageDone property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDamageDone() {
        return damageDone;
    }

    /**
     * Sets the value of the damageDone property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDamageDone(BigInteger value) {
        this.damageDone = value;
    }

    /**
     * Gets the value of the finalBlow property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFinalBlow() {
        return finalBlow;
    }

    /**
     * Sets the value of the finalBlow property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFinalBlow(BigInteger value) {
        this.finalBlow = value;
    }

    /**
     * Gets the value of the flag property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFlag() {
        return flag;
    }

    /**
     * Sets the value of the flag property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFlag(BigInteger value) {
        this.flag = value;
    }

    /**
     * Gets the value of the killID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getKillID() {
        return killID;
    }

    /**
     * Sets the value of the killID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setKillID(BigInteger value) {
        this.killID = value;
    }

    /**
     * Gets the value of the killTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKillTime() {
        return killTime;
    }

    /**
     * Sets the value of the killTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKillTime(String value) {
        this.killTime = value;
    }

    /**
     * Gets the value of the moonID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMoonID() {
        return moonID;
    }

    /**
     * Sets the value of the moonID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMoonID(BigInteger value) {
        this.moonID = value;
    }

    /**
     * Gets the value of the qtyDestroyed property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getQtyDestroyed() {
        return qtyDestroyed;
    }

    /**
     * Sets the value of the qtyDestroyed property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setQtyDestroyed(BigInteger value) {
        this.qtyDestroyed = value;
    }

    /**
     * Gets the value of the qtyDropped property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getQtyDropped() {
        return qtyDropped;
    }

    /**
     * Sets the value of the qtyDropped property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setQtyDropped(BigInteger value) {
        this.qtyDropped = value;
    }

    /**
     * Gets the value of the securityStatus property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSecurityStatus() {
        return securityStatus;
    }

    /**
     * Sets the value of the securityStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSecurityStatus(BigDecimal value) {
        this.securityStatus = value;
    }

    /**
     * Gets the value of the shipTypeID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getShipTypeID() {
        return shipTypeID;
    }

    /**
     * Sets the value of the shipTypeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setShipTypeID(BigInteger value) {
        this.shipTypeID = value;
    }

    /**
     * Gets the value of the solarSystemID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSolarSystemID() {
        return solarSystemID;
    }

    /**
     * Sets the value of the solarSystemID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSolarSystemID(BigInteger value) {
        this.solarSystemID = value;
    }

    /**
     * Gets the value of the typeID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTypeID() {
        return typeID;
    }

    /**
     * Sets the value of the typeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTypeID(BigInteger value) {
        this.typeID = value;
    }

    /**
     * Gets the value of the weaponTypeID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getWeaponTypeID() {
        return weaponTypeID;
    }

    /**
     * Sets the value of the weaponTypeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWeaponTypeID(BigInteger value) {
        this.weaponTypeID = value;
    }

}
