//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.04.30 at 05:11:16 PM CEST 
//


package model.api.eve.skilltree;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{}rowset"/>
 *         &lt;element ref="{}description"/>
 *         &lt;element ref="{}rank"/>
 *         &lt;element ref="{}requiredAttributes"/>
 *       &lt;/choice>
 *       &lt;attribute name="bonusType" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="bonusValue" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="groupID" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="groupName" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="skillLevel" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="typeID" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="typeName" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rowsetOrDescriptionOrRank"
})
@XmlRootElement(name = "row")
public class Row {

    @XmlElements({
        @XmlElement(name = "description", type = String.class),
        @XmlElement(name = "requiredAttributes", type = RequiredAttributes.class),
        @XmlElement(name = "rowset", type = Rowset.class),
        @XmlElement(name = "rank", type = BigInteger.class)
    })
    protected List<Object> rowsetOrDescriptionOrRank;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String bonusType;
    @XmlAttribute
    protected BigInteger bonusValue;
    @XmlAttribute
    protected BigInteger groupID;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String groupName;
    @XmlAttribute
    protected BigInteger skillLevel;
    @XmlAttribute
    protected BigInteger typeID;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String typeName;

    /**
     * Gets the value of the rowsetOrDescriptionOrRank property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rowsetOrDescriptionOrRank property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRowsetOrDescriptionOrRank().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * {@link RequiredAttributes }
     * {@link Rowset }
     * {@link BigInteger }
     * 
     * 
     */
    public List<Object> getRowsetOrDescriptionOrRank() {
        if (rowsetOrDescriptionOrRank == null) {
            rowsetOrDescriptionOrRank = new ArrayList<Object>();
        }
        return this.rowsetOrDescriptionOrRank;
    }

    /**
     * Gets the value of the bonusType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBonusType() {
        return bonusType;
    }

    /**
     * Sets the value of the bonusType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBonusType(String value) {
        this.bonusType = value;
    }

    /**
     * Gets the value of the bonusValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBonusValue() {
        return bonusValue;
    }

    /**
     * Sets the value of the bonusValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBonusValue(BigInteger value) {
        this.bonusValue = value;
    }

    /**
     * Gets the value of the groupID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGroupID() {
        return groupID;
    }

    /**
     * Sets the value of the groupID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGroupID(BigInteger value) {
        this.groupID = value;
    }

    /**
     * Gets the value of the groupName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * Sets the value of the groupName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupName(String value) {
        this.groupName = value;
    }

    /**
     * Gets the value of the skillLevel property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSkillLevel() {
        return skillLevel;
    }

    /**
     * Sets the value of the skillLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSkillLevel(BigInteger value) {
        this.skillLevel = value;
    }

    /**
     * Gets the value of the typeID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTypeID() {
        return typeID;
    }

    /**
     * Sets the value of the typeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTypeID(BigInteger value) {
        this.typeID = value;
    }

    /**
     * Gets the value of the typeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * Sets the value of the typeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeName(String value) {
        this.typeName = value;
    }

}
