//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.04.30 at 05:10:54 PM CEST 
//


package model.api.character.factionalwarfarestats;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the api.character.factionalwarfarestats package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _KillsTotal_QNAME = new QName("", "killsTotal");
    private final static QName _VictoryPointsLastWeek_QNAME = new QName("", "victoryPointsLastWeek");
    private final static QName _CachedUntil_QNAME = new QName("", "cachedUntil");
    private final static QName _Enlisted_QNAME = new QName("", "enlisted");
    private final static QName _CurrentRank_QNAME = new QName("", "currentRank");
    private final static QName _KillsLastWeek_QNAME = new QName("", "killsLastWeek");
    private final static QName _FactionID_QNAME = new QName("", "factionID");
    private final static QName _HighestRank_QNAME = new QName("", "highestRank");
    private final static QName _CurrentTime_QNAME = new QName("", "currentTime");
    private final static QName _FactionName_QNAME = new QName("", "factionName");
    private final static QName _KillsYesterday_QNAME = new QName("", "killsYesterday");
    private final static QName _VictoryPointsTotal_QNAME = new QName("", "victoryPointsTotal");
    private final static QName _VictoryPointsYesterday_QNAME = new QName("", "victoryPointsYesterday");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: api.character.factionalwarfarestats
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Eveapi }
     * 
     */
    public Eveapi createEveapi() {
        return new Eveapi();
    }

    /**
     * Create an instance of {@link Result }
     * 
     */
    public Result createResult() {
        return new Result();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "killsTotal")
    public JAXBElement<BigInteger> createKillsTotal(BigInteger value) {
        return new JAXBElement<BigInteger>(_KillsTotal_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "victoryPointsLastWeek")
    public JAXBElement<BigInteger> createVictoryPointsLastWeek(BigInteger value) {
        return new JAXBElement<BigInteger>(_VictoryPointsLastWeek_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "cachedUntil")
    public JAXBElement<String> createCachedUntil(String value) {
        return new JAXBElement<String>(_CachedUntil_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "enlisted")
    public JAXBElement<String> createEnlisted(String value) {
        return new JAXBElement<String>(_Enlisted_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "currentRank")
    public JAXBElement<BigInteger> createCurrentRank(BigInteger value) {
        return new JAXBElement<BigInteger>(_CurrentRank_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "killsLastWeek")
    public JAXBElement<BigInteger> createKillsLastWeek(BigInteger value) {
        return new JAXBElement<BigInteger>(_KillsLastWeek_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "factionID")
    public JAXBElement<BigInteger> createFactionID(BigInteger value) {
        return new JAXBElement<BigInteger>(_FactionID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "highestRank")
    public JAXBElement<BigInteger> createHighestRank(BigInteger value) {
        return new JAXBElement<BigInteger>(_HighestRank_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "currentTime")
    public JAXBElement<String> createCurrentTime(String value) {
        return new JAXBElement<String>(_CurrentTime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "factionName")
    public JAXBElement<String> createFactionName(String value) {
        return new JAXBElement<String>(_FactionName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "killsYesterday")
    public JAXBElement<BigInteger> createKillsYesterday(BigInteger value) {
        return new JAXBElement<BigInteger>(_KillsYesterday_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "victoryPointsTotal")
    public JAXBElement<BigInteger> createVictoryPointsTotal(BigInteger value) {
        return new JAXBElement<BigInteger>(_VictoryPointsTotal_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "victoryPointsYesterday")
    public JAXBElement<BigInteger> createVictoryPointsYesterday(BigInteger value) {
        return new JAXBElement<BigInteger>(_VictoryPointsYesterday_QNAME, BigInteger.class, null, value);
    }

}
