//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.04.30 at 05:11:08 PM CEST 
//


package model.api.corporation.posdetails;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}onStandingDrop"/>
 *         &lt;element ref="{}onStatusDrop"/>
 *         &lt;element ref="{}onAggression"/>
 *         &lt;element ref="{}onCorporationWar"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "onStandingDrop",
    "onStatusDrop",
    "onAggression",
    "onCorporationWar"
})
@XmlRootElement(name = "combatSettings")
public class CombatSettings {

    @XmlElement(required = true)
    protected OnStandingDrop onStandingDrop;
    @XmlElement(required = true)
    protected OnStatusDrop onStatusDrop;
    @XmlElement(required = true)
    protected OnAggression onAggression;
    @XmlElement(required = true)
    protected OnCorporationWar onCorporationWar;

    /**
     * Gets the value of the onStandingDrop property.
     * 
     * @return
     *     possible object is
     *     {@link OnStandingDrop }
     *     
     */
    public OnStandingDrop getOnStandingDrop() {
        return onStandingDrop;
    }

    /**
     * Sets the value of the onStandingDrop property.
     * 
     * @param value
     *     allowed object is
     *     {@link OnStandingDrop }
     *     
     */
    public void setOnStandingDrop(OnStandingDrop value) {
        this.onStandingDrop = value;
    }

    /**
     * Gets the value of the onStatusDrop property.
     * 
     * @return
     *     possible object is
     *     {@link OnStatusDrop }
     *     
     */
    public OnStatusDrop getOnStatusDrop() {
        return onStatusDrop;
    }

    /**
     * Sets the value of the onStatusDrop property.
     * 
     * @param value
     *     allowed object is
     *     {@link OnStatusDrop }
     *     
     */
    public void setOnStatusDrop(OnStatusDrop value) {
        this.onStatusDrop = value;
    }

    /**
     * Gets the value of the onAggression property.
     * 
     * @return
     *     possible object is
     *     {@link OnAggression }
     *     
     */
    public OnAggression getOnAggression() {
        return onAggression;
    }

    /**
     * Sets the value of the onAggression property.
     * 
     * @param value
     *     allowed object is
     *     {@link OnAggression }
     *     
     */
    public void setOnAggression(OnAggression value) {
        this.onAggression = value;
    }

    /**
     * Gets the value of the onCorporationWar property.
     * 
     * @return
     *     possible object is
     *     {@link OnCorporationWar }
     *     
     */
    public OnCorporationWar getOnCorporationWar() {
        return onCorporationWar;
    }

    /**
     * Sets the value of the onCorporationWar property.
     * 
     * @param value
     *     allowed object is
     *     {@link OnCorporationWar }
     *     
     */
    public void setOnCorporationWar(OnCorporationWar value) {
        this.onCorporationWar = value;
    }

}
