//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.04.30 at 05:11:08 PM CEST 
//


package model.api.corporation.posdetails;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}usageFlags"/>
 *         &lt;element ref="{}deployFlags"/>
 *         &lt;element ref="{}allowCorporationMembers"/>
 *         &lt;element ref="{}allowAllianceMembers"/>
 *         &lt;element ref="{}claimSovereignty"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "usageFlags",
    "deployFlags",
    "allowCorporationMembers",
    "allowAllianceMembers",
    "claimSovereignty"
})
@XmlRootElement(name = "generalSettings")
public class GeneralSettings {

    @XmlElement(required = true)
    protected BigInteger usageFlags;
    @XmlElement(required = true)
    protected BigInteger deployFlags;
    @XmlElement(required = true)
    protected BigInteger allowCorporationMembers;
    @XmlElement(required = true)
    protected BigInteger allowAllianceMembers;
    @XmlElement(required = true)
    protected BigInteger claimSovereignty;

    /**
     * Gets the value of the usageFlags property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUsageFlags() {
        return usageFlags;
    }

    /**
     * Sets the value of the usageFlags property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUsageFlags(BigInteger value) {
        this.usageFlags = value;
    }

    /**
     * Gets the value of the deployFlags property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDeployFlags() {
        return deployFlags;
    }

    /**
     * Sets the value of the deployFlags property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDeployFlags(BigInteger value) {
        this.deployFlags = value;
    }

    /**
     * Gets the value of the allowCorporationMembers property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAllowCorporationMembers() {
        return allowCorporationMembers;
    }

    /**
     * Sets the value of the allowCorporationMembers property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAllowCorporationMembers(BigInteger value) {
        this.allowCorporationMembers = value;
    }

    /**
     * Gets the value of the allowAllianceMembers property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAllowAllianceMembers() {
        return allowAllianceMembers;
    }

    /**
     * Sets the value of the allowAllianceMembers property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAllowAllianceMembers(BigInteger value) {
        this.allowAllianceMembers = value;
    }

    /**
     * Gets the value of the claimSovereignty property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getClaimSovereignty() {
        return claimSovereignty;
    }

    /**
     * Sets the value of the claimSovereignty property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setClaimSovereignty(BigInteger value) {
        this.claimSovereignty = value;
    }

}
