//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.04.30 at 05:11:08 PM CEST 
//


package model.api.corporation.posdetails;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the api.corporation.posdetails package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CurrentTime_QNAME = new QName("", "currentTime");
    private final static QName _OnlineTimestamp_QNAME = new QName("", "onlineTimestamp");
    private final static QName _StateTimestamp_QNAME = new QName("", "stateTimestamp");
    private final static QName _CachedUntil_QNAME = new QName("", "cachedUntil");
    private final static QName _DeployFlags_QNAME = new QName("", "deployFlags");
    private final static QName _UsageFlags_QNAME = new QName("", "usageFlags");
    private final static QName _State_QNAME = new QName("", "state");
    private final static QName _ClaimSovereignty_QNAME = new QName("", "claimSovereignty");
    private final static QName _AllowAllianceMembers_QNAME = new QName("", "allowAllianceMembers");
    private final static QName _AllowCorporationMembers_QNAME = new QName("", "allowCorporationMembers");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: api.corporation.posdetails
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Row }
     * 
     */
    public Row createRow() {
        return new Row();
    }

    /**
     * Create an instance of {@link OnStatusDrop }
     * 
     */
    public OnStatusDrop createOnStatusDrop() {
        return new OnStatusDrop();
    }

    /**
     * Create an instance of {@link OnStandingDrop }
     * 
     */
    public OnStandingDrop createOnStandingDrop() {
        return new OnStandingDrop();
    }

    /**
     * Create an instance of {@link OnAggression }
     * 
     */
    public OnAggression createOnAggression() {
        return new OnAggression();
    }

    /**
     * Create an instance of {@link Eveapi }
     * 
     */
    public Eveapi createEveapi() {
        return new Eveapi();
    }

    /**
     * Create an instance of {@link OnCorporationWar }
     * 
     */
    public OnCorporationWar createOnCorporationWar() {
        return new OnCorporationWar();
    }

    /**
     * Create an instance of {@link CombatSettings }
     * 
     */
    public CombatSettings createCombatSettings() {
        return new CombatSettings();
    }

    /**
     * Create an instance of {@link GeneralSettings }
     * 
     */
    public GeneralSettings createGeneralSettings() {
        return new GeneralSettings();
    }

    /**
     * Create an instance of {@link Result }
     * 
     */
    public Result createResult() {
        return new Result();
    }

    /**
     * Create an instance of {@link Rowset }
     * 
     */
    public Rowset createRowset() {
        return new Rowset();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "currentTime")
    public JAXBElement<String> createCurrentTime(String value) {
        return new JAXBElement<String>(_CurrentTime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "onlineTimestamp")
    public JAXBElement<String> createOnlineTimestamp(String value) {
        return new JAXBElement<String>(_OnlineTimestamp_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "stateTimestamp")
    public JAXBElement<String> createStateTimestamp(String value) {
        return new JAXBElement<String>(_StateTimestamp_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "cachedUntil")
    public JAXBElement<String> createCachedUntil(String value) {
        return new JAXBElement<String>(_CachedUntil_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "deployFlags")
    public JAXBElement<BigInteger> createDeployFlags(BigInteger value) {
        return new JAXBElement<BigInteger>(_DeployFlags_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "usageFlags")
    public JAXBElement<BigInteger> createUsageFlags(BigInteger value) {
        return new JAXBElement<BigInteger>(_UsageFlags_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "state")
    public JAXBElement<BigInteger> createState(BigInteger value) {
        return new JAXBElement<BigInteger>(_State_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "claimSovereignty")
    public JAXBElement<BigInteger> createClaimSovereignty(BigInteger value) {
        return new JAXBElement<BigInteger>(_ClaimSovereignty_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "allowAllianceMembers")
    public JAXBElement<BigInteger> createAllowAllianceMembers(BigInteger value) {
        return new JAXBElement<BigInteger>(_AllowAllianceMembers_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "allowCorporationMembers")
    public JAXBElement<BigInteger> createAllowCorporationMembers(BigInteger value) {
        return new JAXBElement<BigInteger>(_AllowCorporationMembers_QNAME, BigInteger.class, null, value);
    }

}
