//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.04.30 at 05:11:17 PM CEST 
//


package model.api.map.factionalwarfaresystems;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="contested" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="occupyingFactionID" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="occupyingFactionName" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="solarSystemID" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="solarSystemName" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "row")
public class Row {

    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String contested;
    @XmlAttribute(required = true)
    protected BigInteger occupyingFactionID;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String occupyingFactionName;
    @XmlAttribute(required = true)
    protected BigInteger solarSystemID;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String solarSystemName;

    /**
     * Gets the value of the contested property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContested() {
        return contested;
    }

    /**
     * Sets the value of the contested property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContested(String value) {
        this.contested = value;
    }

    /**
     * Gets the value of the occupyingFactionID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOccupyingFactionID() {
        return occupyingFactionID;
    }

    /**
     * Sets the value of the occupyingFactionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOccupyingFactionID(BigInteger value) {
        this.occupyingFactionID = value;
    }

    /**
     * Gets the value of the occupyingFactionName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOccupyingFactionName() {
        return occupyingFactionName;
    }

    /**
     * Sets the value of the occupyingFactionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOccupyingFactionName(String value) {
        this.occupyingFactionName = value;
    }

    /**
     * Gets the value of the solarSystemID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSolarSystemID() {
        return solarSystemID;
    }

    /**
     * Sets the value of the solarSystemID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSolarSystemID(BigInteger value) {
        this.solarSystemID = value;
    }

    /**
     * Gets the value of the solarSystemName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSolarSystemName() {
        return solarSystemName;
    }

    /**
     * Sets the value of the solarSystemName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSolarSystemName(String value) {
        this.solarSystemName = value;
    }

}
