//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.04.30 at 05:11:02 PM CEST 
//


package model.api.corporation.corporationsheet;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}graphicID"/>
 *         &lt;element ref="{}shape1"/>
 *         &lt;element ref="{}shape2"/>
 *         &lt;element ref="{}shape3"/>
 *         &lt;element ref="{}color1"/>
 *         &lt;element ref="{}color2"/>
 *         &lt;element ref="{}color3"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "graphicID",
    "shape1",
    "shape2",
    "shape3",
    "color1",
    "color2",
    "color3"
})
@XmlRootElement(name = "logo")
public class Logo {

    @XmlElement(required = true)
    protected BigInteger graphicID;
    @XmlElement(required = true)
    protected BigInteger shape1;
    @XmlElement(required = true)
    protected BigInteger shape2;
    @XmlElement(required = true)
    protected BigInteger shape3;
    @XmlElement(required = true)
    protected BigInteger color1;
    @XmlElement(required = true)
    protected BigInteger color2;
    @XmlElement(required = true)
    protected BigInteger color3;

    /**
     * Gets the value of the graphicID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGraphicID() {
        return graphicID;
    }

    /**
     * Sets the value of the graphicID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGraphicID(BigInteger value) {
        this.graphicID = value;
    }

    /**
     * Gets the value of the shape1 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getShape1() {
        return shape1;
    }

    /**
     * Sets the value of the shape1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setShape1(BigInteger value) {
        this.shape1 = value;
    }

    /**
     * Gets the value of the shape2 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getShape2() {
        return shape2;
    }

    /**
     * Sets the value of the shape2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setShape2(BigInteger value) {
        this.shape2 = value;
    }

    /**
     * Gets the value of the shape3 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getShape3() {
        return shape3;
    }

    /**
     * Sets the value of the shape3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setShape3(BigInteger value) {
        this.shape3 = value;
    }

    /**
     * Gets the value of the color1 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getColor1() {
        return color1;
    }

    /**
     * Sets the value of the color1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setColor1(BigInteger value) {
        this.color1 = value;
    }

    /**
     * Gets the value of the color2 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getColor2() {
        return color2;
    }

    /**
     * Sets the value of the color2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setColor2(BigInteger value) {
        this.color2 = value;
    }

    /**
     * Gets the value of the color3 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getColor3() {
        return color3;
    }

    /**
     * Sets the value of the color3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setColor3(BigInteger value) {
        this.color3 = value;
    }

}
