//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.04.30 at 05:10:54 PM CEST 
//


package model.api.character.industryjobs;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="activityID" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="assemblyLineID" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="beginProductionTime" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="charMaterialMultiplier" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="charTimeMultiplier" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="completed" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="completedStatus" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="completedSuccessfully" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="containerID" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="containerLocationID" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="containerTypeID" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="endProductionTime" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="installTime" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="installedInSolarSystemID" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="installedItemCopy" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="installedItemFlag" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="installedItemID" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="installedItemLicensedProductionRunsRemaining" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="installedItemLocationID" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="installedItemMaterialLevel" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="installedItemProductivityLevel" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="installedItemQuantity" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="installedItemTypeID" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="installerID" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="jobID" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="licensedProductionRuns" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="materialMultiplier" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="outputFlag" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="outputLocationID" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="outputTypeID" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="pauseProductionTime" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="runs" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="timeMultiplier" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "row")
public class Row {

    @XmlAttribute(required = true)
    protected BigInteger activityID;
    @XmlAttribute(required = true)
    protected BigInteger assemblyLineID;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String beginProductionTime;
    @XmlAttribute(required = true)
    protected BigInteger charMaterialMultiplier;
    @XmlAttribute(required = true)
    protected BigDecimal charTimeMultiplier;
    @XmlAttribute(required = true)
    protected BigInteger completed;
    @XmlAttribute(required = true)
    protected BigInteger completedStatus;
    @XmlAttribute(required = true)
    protected BigInteger completedSuccessfully;
    @XmlAttribute(required = true)
    protected BigInteger containerID;
    @XmlAttribute(required = true)
    protected BigInteger containerLocationID;
    @XmlAttribute(required = true)
    protected BigInteger containerTypeID;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String endProductionTime;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String installTime;
    @XmlAttribute(required = true)
    protected BigInteger installedInSolarSystemID;
    @XmlAttribute(required = true)
    protected BigInteger installedItemCopy;
    @XmlAttribute(required = true)
    protected BigInteger installedItemFlag;
    @XmlAttribute(required = true)
    protected BigInteger installedItemID;
    @XmlAttribute(required = true)
    protected BigInteger installedItemLicensedProductionRunsRemaining;
    @XmlAttribute(required = true)
    protected BigInteger installedItemLocationID;
    @XmlAttribute(required = true)
    protected BigInteger installedItemMaterialLevel;
    @XmlAttribute(required = true)
    protected BigInteger installedItemProductivityLevel;
    @XmlAttribute(required = true)
    protected BigInteger installedItemQuantity;
    @XmlAttribute(required = true)
    protected BigInteger installedItemTypeID;
    @XmlAttribute(required = true)
    protected BigInteger installerID;
    @XmlAttribute(required = true)
    protected BigInteger jobID;
    @XmlAttribute(required = true)
    protected BigInteger licensedProductionRuns;
    @XmlAttribute(required = true)
    protected BigInteger materialMultiplier;
    @XmlAttribute(required = true)
    protected BigInteger outputFlag;
    @XmlAttribute(required = true)
    protected BigInteger outputLocationID;
    @XmlAttribute(required = true)
    protected BigInteger outputTypeID;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String pauseProductionTime;
    @XmlAttribute(required = true)
    protected BigInteger runs;
    @XmlAttribute(required = true)
    protected BigDecimal timeMultiplier;

    /**
     * Gets the value of the activityID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getActivityID() {
        return activityID;
    }

    /**
     * Sets the value of the activityID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setActivityID(BigInteger value) {
        this.activityID = value;
    }

    /**
     * Gets the value of the assemblyLineID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAssemblyLineID() {
        return assemblyLineID;
    }

    /**
     * Sets the value of the assemblyLineID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAssemblyLineID(BigInteger value) {
        this.assemblyLineID = value;
    }

    /**
     * Gets the value of the beginProductionTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBeginProductionTime() {
        return beginProductionTime;
    }

    /**
     * Sets the value of the beginProductionTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBeginProductionTime(String value) {
        this.beginProductionTime = value;
    }

    /**
     * Gets the value of the charMaterialMultiplier property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCharMaterialMultiplier() {
        return charMaterialMultiplier;
    }

    /**
     * Sets the value of the charMaterialMultiplier property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCharMaterialMultiplier(BigInteger value) {
        this.charMaterialMultiplier = value;
    }

    /**
     * Gets the value of the charTimeMultiplier property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCharTimeMultiplier() {
        return charTimeMultiplier;
    }

    /**
     * Sets the value of the charTimeMultiplier property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCharTimeMultiplier(BigDecimal value) {
        this.charTimeMultiplier = value;
    }

    /**
     * Gets the value of the completed property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCompleted() {
        return completed;
    }

    /**
     * Sets the value of the completed property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCompleted(BigInteger value) {
        this.completed = value;
    }

    /**
     * Gets the value of the completedStatus property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCompletedStatus() {
        return completedStatus;
    }

    /**
     * Sets the value of the completedStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCompletedStatus(BigInteger value) {
        this.completedStatus = value;
    }

    /**
     * Gets the value of the completedSuccessfully property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCompletedSuccessfully() {
        return completedSuccessfully;
    }

    /**
     * Sets the value of the completedSuccessfully property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCompletedSuccessfully(BigInteger value) {
        this.completedSuccessfully = value;
    }

    /**
     * Gets the value of the containerID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getContainerID() {
        return containerID;
    }

    /**
     * Sets the value of the containerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setContainerID(BigInteger value) {
        this.containerID = value;
    }

    /**
     * Gets the value of the containerLocationID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getContainerLocationID() {
        return containerLocationID;
    }

    /**
     * Sets the value of the containerLocationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setContainerLocationID(BigInteger value) {
        this.containerLocationID = value;
    }

    /**
     * Gets the value of the containerTypeID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getContainerTypeID() {
        return containerTypeID;
    }

    /**
     * Sets the value of the containerTypeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setContainerTypeID(BigInteger value) {
        this.containerTypeID = value;
    }

    /**
     * Gets the value of the endProductionTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndProductionTime() {
        return endProductionTime;
    }

    /**
     * Sets the value of the endProductionTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndProductionTime(String value) {
        this.endProductionTime = value;
    }

    /**
     * Gets the value of the installTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstallTime() {
        return installTime;
    }

    /**
     * Sets the value of the installTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstallTime(String value) {
        this.installTime = value;
    }

    /**
     * Gets the value of the installedInSolarSystemID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getInstalledInSolarSystemID() {
        return installedInSolarSystemID;
    }

    /**
     * Sets the value of the installedInSolarSystemID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setInstalledInSolarSystemID(BigInteger value) {
        this.installedInSolarSystemID = value;
    }

    /**
     * Gets the value of the installedItemCopy property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getInstalledItemCopy() {
        return installedItemCopy;
    }

    /**
     * Sets the value of the installedItemCopy property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setInstalledItemCopy(BigInteger value) {
        this.installedItemCopy = value;
    }

    /**
     * Gets the value of the installedItemFlag property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getInstalledItemFlag() {
        return installedItemFlag;
    }

    /**
     * Sets the value of the installedItemFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setInstalledItemFlag(BigInteger value) {
        this.installedItemFlag = value;
    }

    /**
     * Gets the value of the installedItemID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getInstalledItemID() {
        return installedItemID;
    }

    /**
     * Sets the value of the installedItemID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setInstalledItemID(BigInteger value) {
        this.installedItemID = value;
    }

    /**
     * Gets the value of the installedItemLicensedProductionRunsRemaining property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getInstalledItemLicensedProductionRunsRemaining() {
        return installedItemLicensedProductionRunsRemaining;
    }

    /**
     * Sets the value of the installedItemLicensedProductionRunsRemaining property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setInstalledItemLicensedProductionRunsRemaining(BigInteger value) {
        this.installedItemLicensedProductionRunsRemaining = value;
    }

    /**
     * Gets the value of the installedItemLocationID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getInstalledItemLocationID() {
        return installedItemLocationID;
    }

    /**
     * Sets the value of the installedItemLocationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setInstalledItemLocationID(BigInteger value) {
        this.installedItemLocationID = value;
    }

    /**
     * Gets the value of the installedItemMaterialLevel property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getInstalledItemMaterialLevel() {
        return installedItemMaterialLevel;
    }

    /**
     * Sets the value of the installedItemMaterialLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setInstalledItemMaterialLevel(BigInteger value) {
        this.installedItemMaterialLevel = value;
    }

    /**
     * Gets the value of the installedItemProductivityLevel property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getInstalledItemProductivityLevel() {
        return installedItemProductivityLevel;
    }

    /**
     * Sets the value of the installedItemProductivityLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setInstalledItemProductivityLevel(BigInteger value) {
        this.installedItemProductivityLevel = value;
    }

    /**
     * Gets the value of the installedItemQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getInstalledItemQuantity() {
        return installedItemQuantity;
    }

    /**
     * Sets the value of the installedItemQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setInstalledItemQuantity(BigInteger value) {
        this.installedItemQuantity = value;
    }

    /**
     * Gets the value of the installedItemTypeID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getInstalledItemTypeID() {
        return installedItemTypeID;
    }

    /**
     * Sets the value of the installedItemTypeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setInstalledItemTypeID(BigInteger value) {
        this.installedItemTypeID = value;
    }

    /**
     * Gets the value of the installerID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getInstallerID() {
        return installerID;
    }

    /**
     * Sets the value of the installerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setInstallerID(BigInteger value) {
        this.installerID = value;
    }

    /**
     * Gets the value of the jobID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getJobID() {
        return jobID;
    }

    /**
     * Sets the value of the jobID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setJobID(BigInteger value) {
        this.jobID = value;
    }

    /**
     * Gets the value of the licensedProductionRuns property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLicensedProductionRuns() {
        return licensedProductionRuns;
    }

    /**
     * Sets the value of the licensedProductionRuns property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLicensedProductionRuns(BigInteger value) {
        this.licensedProductionRuns = value;
    }

    /**
     * Gets the value of the materialMultiplier property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaterialMultiplier() {
        return materialMultiplier;
    }

    /**
     * Sets the value of the materialMultiplier property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaterialMultiplier(BigInteger value) {
        this.materialMultiplier = value;
    }

    /**
     * Gets the value of the outputFlag property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOutputFlag() {
        return outputFlag;
    }

    /**
     * Sets the value of the outputFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOutputFlag(BigInteger value) {
        this.outputFlag = value;
    }

    /**
     * Gets the value of the outputLocationID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOutputLocationID() {
        return outputLocationID;
    }

    /**
     * Sets the value of the outputLocationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOutputLocationID(BigInteger value) {
        this.outputLocationID = value;
    }

    /**
     * Gets the value of the outputTypeID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOutputTypeID() {
        return outputTypeID;
    }

    /**
     * Sets the value of the outputTypeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOutputTypeID(BigInteger value) {
        this.outputTypeID = value;
    }

    /**
     * Gets the value of the pauseProductionTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPauseProductionTime() {
        return pauseProductionTime;
    }

    /**
     * Sets the value of the pauseProductionTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPauseProductionTime(String value) {
        this.pauseProductionTime = value;
    }

    /**
     * Gets the value of the runs property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRuns() {
        return runs;
    }

    /**
     * Sets the value of the runs property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRuns(BigInteger value) {
        this.runs = value;
    }

    /**
     * Gets the value of the timeMultiplier property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTimeMultiplier() {
        return timeMultiplier;
    }

    /**
     * Sets the value of the timeMultiplier property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTimeMultiplier(BigDecimal value) {
        this.timeMultiplier = value;
    }

}
