//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.04.30 at 05:10:53 PM CEST 
//


package model.api.character.charactersheet;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}intelligence"/>
 *         &lt;element ref="{}memory"/>
 *         &lt;element ref="{}charisma"/>
 *         &lt;element ref="{}perception"/>
 *         &lt;element ref="{}willpower"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "intelligence",
    "memory",
    "charisma",
    "perception",
    "willpower"
})
@XmlRootElement(name = "attributes")
public class Attributes {

    @XmlElement(required = true)
    protected BigInteger intelligence;
    @XmlElement(required = true)
    protected BigInteger memory;
    @XmlElement(required = true)
    protected BigInteger charisma;
    @XmlElement(required = true)
    protected BigInteger perception;
    @XmlElement(required = true)
    protected BigInteger willpower;

    /**
     * Gets the value of the intelligence property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIntelligence() {
        return intelligence;
    }

    /**
     * Sets the value of the intelligence property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIntelligence(BigInteger value) {
        this.intelligence = value;
    }

    /**
     * Gets the value of the memory property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMemory() {
        return memory;
    }

    /**
     * Sets the value of the memory property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMemory(BigInteger value) {
        this.memory = value;
    }

    /**
     * Gets the value of the charisma property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCharisma() {
        return charisma;
    }

    /**
     * Sets the value of the charisma property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCharisma(BigInteger value) {
        this.charisma = value;
    }

    /**
     * Gets the value of the perception property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPerception() {
        return perception;
    }

    /**
     * Sets the value of the perception property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPerception(BigInteger value) {
        this.perception = value;
    }

    /**
     * Gets the value of the willpower property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getWillpower() {
        return willpower;
    }

    /**
     * Sets the value of the willpower property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWillpower(BigInteger value) {
        this.willpower = value;
    }

}
