//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.04.30 at 05:10:53 PM CEST 
//


package model.api.character.charactersheet;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the api.character.charactersheet package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CloneSkillPoints_QNAME = new QName("", "cloneSkillPoints");
    private final static QName _CachedUntil_QNAME = new QName("", "cachedUntil");
    private final static QName _AugmentatorValue_QNAME = new QName("", "augmentatorValue");
    private final static QName _Perception_QNAME = new QName("", "perception");
    private final static QName _CorporationName_QNAME = new QName("", "corporationName");
    private final static QName _CorporationID_QNAME = new QName("", "corporationID");
    private final static QName _Race_QNAME = new QName("", "race");
    private final static QName _Memory_QNAME = new QName("", "memory");
    private final static QName _CharacterID_QNAME = new QName("", "characterID");
    private final static QName _CurrentTime_QNAME = new QName("", "currentTime");
    private final static QName _Balance_QNAME = new QName("", "balance");
    private final static QName _Willpower_QNAME = new QName("", "willpower");
    private final static QName _Charisma_QNAME = new QName("", "charisma");
    private final static QName _Name_QNAME = new QName("", "name");
    private final static QName _BloodLine_QNAME = new QName("", "bloodLine");
    private final static QName _CloneName_QNAME = new QName("", "cloneName");
    private final static QName _AugmentatorName_QNAME = new QName("", "augmentatorName");
    private final static QName _Gender_QNAME = new QName("", "gender");
    private final static QName _Intelligence_QNAME = new QName("", "intelligence");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: api.character.charactersheet
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AttributeEnhancers }
     * 
     */
    public AttributeEnhancers createAttributeEnhancers() {
        return new AttributeEnhancers();
    }

    /**
     * Create an instance of {@link IntelligenceBonus }
     * 
     */
    public IntelligenceBonus createIntelligenceBonus() {
        return new IntelligenceBonus();
    }

    /**
     * Create an instance of {@link MemoryBonus }
     * 
     */
    public MemoryBonus createMemoryBonus() {
        return new MemoryBonus();
    }

    /**
     * Create an instance of {@link Eveapi }
     * 
     */
    public Eveapi createEveapi() {
        return new Eveapi();
    }

    /**
     * Create an instance of {@link Row }
     * 
     */
    public Row createRow() {
        return new Row();
    }

    /**
     * Create an instance of {@link Rowset }
     * 
     */
    public Rowset createRowset() {
        return new Rowset();
    }

    /**
     * Create an instance of {@link Attributes }
     * 
     */
    public Attributes createAttributes() {
        return new Attributes();
    }

    /**
     * Create an instance of {@link Result }
     * 
     */
    public Result createResult() {
        return new Result();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "cloneSkillPoints")
    public JAXBElement<BigInteger> createCloneSkillPoints(BigInteger value) {
        return new JAXBElement<BigInteger>(_CloneSkillPoints_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "cachedUntil")
    public JAXBElement<String> createCachedUntil(String value) {
        return new JAXBElement<String>(_CachedUntil_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "augmentatorValue")
    public JAXBElement<BigInteger> createAugmentatorValue(BigInteger value) {
        return new JAXBElement<BigInteger>(_AugmentatorValue_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "perception")
    public JAXBElement<BigInteger> createPerception(BigInteger value) {
        return new JAXBElement<BigInteger>(_Perception_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "corporationName")
    public JAXBElement<String> createCorporationName(String value) {
        return new JAXBElement<String>(_CorporationName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "corporationID")
    public JAXBElement<BigInteger> createCorporationID(BigInteger value) {
        return new JAXBElement<BigInteger>(_CorporationID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "race")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createRace(String value) {
        return new JAXBElement<String>(_Race_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "memory")
    public JAXBElement<BigInteger> createMemory(BigInteger value) {
        return new JAXBElement<BigInteger>(_Memory_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "characterID")
    public JAXBElement<BigInteger> createCharacterID(BigInteger value) {
        return new JAXBElement<BigInteger>(_CharacterID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "currentTime")
    public JAXBElement<String> createCurrentTime(String value) {
        return new JAXBElement<String>(_CurrentTime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "balance")
    public JAXBElement<BigDecimal> createBalance(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Balance_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "willpower")
    public JAXBElement<BigInteger> createWillpower(BigInteger value) {
        return new JAXBElement<BigInteger>(_Willpower_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "charisma")
    public JAXBElement<BigInteger> createCharisma(BigInteger value) {
        return new JAXBElement<BigInteger>(_Charisma_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "bloodLine")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createBloodLine(String value) {
        return new JAXBElement<String>(_BloodLine_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "cloneName")
    public JAXBElement<String> createCloneName(String value) {
        return new JAXBElement<String>(_CloneName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "augmentatorName")
    public JAXBElement<String> createAugmentatorName(String value) {
        return new JAXBElement<String>(_AugmentatorName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "gender")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createGender(String value) {
        return new JAXBElement<String>(_Gender_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "intelligence")
    public JAXBElement<BigInteger> createIntelligence(BigInteger value) {
        return new JAXBElement<BigInteger>(_Intelligence_QNAME, BigInteger.class, null, value);
    }

}
