# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main_window.ui'
#
# Created: Thu Mar 17 23:49:49 2011
#      by: pyside-uic 0.2.7 running on PySide 1.0.0~rc1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(670, 494)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_3 = QtGui.QWidget(self.centralwidget)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget_3)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_3 = QtGui.QPushButton(self.widget_3)
        self.pushButton_3.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icon17_04.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_3.setFlat(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_3.addWidget(self.pushButton_3)
        self.label_3 = QtGui.QLabel(self.widget_3)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.gridLayout.addWidget(self.widget_3, 2, 5, 1, 1)
        self.widget_4 = QtGui.QWidget(self.centralwidget)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.widget_4)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_4 = QtGui.QPushButton(self.widget_4)
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_4.addWidget(self.pushButton_4)
        self.label_4 = QtGui.QLabel(self.widget_4)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.gridLayout.addWidget(self.widget_4, 2, 6, 1, 1)
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtGui.QPushButton(self.widget)
        self.pushButton.setText("")
        self.pushButton.setAutoDefault(False)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout.addWidget(self.widget, 2, 3, 1, 1)
        self.widget_2 = QtGui.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_2 = QtGui.QPushButton(self.widget_2)
        self.pushButton_2.setText("")
        self.pushButton_2.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.label_2 = QtGui.QLabel(self.widget_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.gridLayout.addWidget(self.widget_2, 2, 4, 1, 1)
        self.widget_5 = QtGui.QWidget(self.centralwidget)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.widget_5)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.manufacturing_calculator_button = QtGui.QPushButton(self.widget_5)
        self.manufacturing_calculator_button.setText("")
        self.manufacturing_calculator_button.setObjectName("manufacturing_calculator_button")
        self.verticalLayout_5.addWidget(self.manufacturing_calculator_button)
        self.label_5 = QtGui.QLabel(self.widget_5)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.gridLayout.addWidget(self.widget_5, 3, 3, 1, 1)
        self.widget_6 = QtGui.QWidget(self.centralwidget)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.widget_6)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.pushButton_9 = QtGui.QPushButton(self.widget_6)
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_9.addWidget(self.pushButton_9)
        self.label_9 = QtGui.QLabel(self.widget_6)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_9.addWidget(self.label_9)
        self.gridLayout.addWidget(self.widget_6, 4, 3, 1, 1)
        self.widget_8 = QtGui.QWidget(self.centralwidget)
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.widget_8)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_6 = QtGui.QPushButton(self.widget_8)
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_6.addWidget(self.pushButton_6)
        self.label_6 = QtGui.QLabel(self.widget_8)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.gridLayout.addWidget(self.widget_8, 3, 4, 1, 1)
        self.widget_9 = QtGui.QWidget(self.centralwidget)
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.widget_9)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButton_7 = QtGui.QPushButton(self.widget_9)
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_7.addWidget(self.pushButton_7)
        self.label_7 = QtGui.QLabel(self.widget_9)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_7.addWidget(self.label_7)
        self.gridLayout.addWidget(self.widget_9, 3, 5, 1, 1)
        self.widget_10 = QtGui.QWidget(self.centralwidget)
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.widget_10)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.research_calculator_button = QtGui.QPushButton(self.widget_10)
        self.research_calculator_button.setText("")
        self.research_calculator_button.setObjectName("research_calculator_button")
        self.verticalLayout_8.addWidget(self.research_calculator_button)
        self.label_8 = QtGui.QLabel(self.widget_10)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_8.addWidget(self.label_8)
        self.gridLayout.addWidget(self.widget_10, 3, 6, 1, 1)
        self.widget_11 = QtGui.QWidget(self.centralwidget)
        self.widget_11.setObjectName("widget_11")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.widget_11)
        self.verticalLayout_10.setMargin(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.pushButton_10 = QtGui.QPushButton(self.widget_11)
        self.pushButton_10.setText("")
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_10.addWidget(self.pushButton_10)
        self.label_10 = QtGui.QLabel(self.widget_11)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_10.addWidget(self.label_10)
        self.gridLayout.addWidget(self.widget_11, 4, 4, 1, 1)
        self.widget_12 = QtGui.QWidget(self.centralwidget)
        self.widget_12.setObjectName("widget_12")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.widget_12)
        self.verticalLayout_11.setMargin(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.pushButton_11 = QtGui.QPushButton(self.widget_12)
        self.pushButton_11.setText("")
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_11.addWidget(self.pushButton_11)
        self.label_11 = QtGui.QLabel(self.widget_12)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_11.addWidget(self.label_11)
        self.gridLayout.addWidget(self.widget_12, 4, 5, 1, 1)
        self.widget_13 = QtGui.QWidget(self.centralwidget)
        self.widget_13.setObjectName("widget_13")
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.widget_13)
        self.verticalLayout_12.setMargin(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.pushButton_12 = QtGui.QPushButton(self.widget_13)
        self.pushButton_12.setText("")
        self.pushButton_12.setObjectName("pushButton_12")
        self.verticalLayout_12.addWidget(self.pushButton_12)
        self.label_12 = QtGui.QLabel(self.widget_13)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_12.addWidget(self.label_12)
        self.gridLayout.addWidget(self.widget_13, 4, 6, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "EVE Suite", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Ship Fitter", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Item Browser", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Asset Viewer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Character Viewer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Manufacturing Calculator", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "POS Fitter", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Mining Calculator", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Refine Calculator", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Research Calculator", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Skill Browser", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Skill Planner", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Travel Planner", None, QtGui.QApplication.UnicodeUTF8))

import rc_main_window_rc
import rc_main_window_rc
